# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# target 'YOUR_APPLICATION_TARGET_NAME_HERE' do
#   pod 'GoogleMaps', '8.1.0'
# end

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'GoogleMaps'

end
