# Uncomment the next line to define a global platform for your project
platform :ios, ’11.0’
pod 'GoogleMaps'
# pod 'FireStore'
# pod 'Firebase/Core'
# pod 'Firebase/Firestore'
target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 # Pods for Runner
end